version: '2'
services:
  front:
    container_name: test.in8.front
    build: ./.docker/node
    env_file: 
      - ./front/.env
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
    networks:
      - dev-net

  back:
    container_name: test.in8.back
    build: ./.docker/php
    restart: always
    ports:
      - '8031:80'
    volumes:
      - ./back:/app
    networks:
      - dev-net

  db:
    container_name: test.in8.db
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Test@3661
      MYSQL_DATABASE: testin8
      MYSQL_USER: testin8
      MYSQL_PASSWORD: Test@3661
    volumes: 
      - ./.db:/var/lib/mysql
    networks:
      - dev-net

networks:
  dev-net:
    external: true